import type { Booking, Cycle, User } from "./types";

export const mockUser: User = {
  id: "u1",
  name: "RTU Student",
  email: "student@rtu.lv",
};

export const mockCycles: Cycle[] = [
  {
    id: "c1",
    name: "Green City Bike",
    type: "city",
    gear: false,
    pricePerHour: 2,
    locationName: "RTU Main Campus",
    lat: 56.9497,
    lng: 24.1,
    isAvailableNow: true,
    rating: 4.5,
  },
  {
    id: "c2",
    name: "Blue Commuter",
    type: "city",
    gear: true,
    pricePerHour: 2.5,
    locationName: "RTU Hostel",
    lat: 56.947,
    lng: 24.108,
    isAvailableNow: false,
    nextAvailableTime: "Today 18:00",
    rating: 4.2,
  },
  {
    id: "c3",
    name: "Red MTB",
    type: "mtb",
    gear: true,
    pricePerHour: 3,
    locationName: "Old Town Stand",
    lat: 56.9496,
    lng: 24.1052,
    isAvailableNow: true,
    rating: 4.8,
  },
  {
    id: "c4",
    name: "Campus Cruiser",
    type: "city",
    gear: true,
    pricePerHour: 2.2,
    locationName: "RTU Library",
    lat: 56.9504,
    lng: 24.113,
    isAvailableNow: true,
    rating: 4.4,
  },
  {
    id: "c5",
    name: "Yellow Roadster",
    type: "road",
    gear: true,
    pricePerHour: 3.2,
    locationName: "Daugava Riverside Path",
    lat: 56.9485,
    lng: 24.099,
    isAvailableNow: true,
    rating: 4.7,
  },
  {
    id: "c6",
    name: "Hostel Hybrid",
    type: "city",
    gear: true,
    pricePerHour: 2.1,
    locationName: "RTU Student Hostel Courtyard",
    lat: 56.9462,
    lng: 24.111,
    isAvailableNow: true,
    rating: 4.3,
  },
];

export const mockBookings: Booking[] = [
  {
    id: "b1",
    cycleId: "c1",
    userId: "u1",
    startTime: "2025-12-01T10:00:00Z",
    endTime: "2025-12-01T11:00:00Z",
    pricePaid: 2,
    distanceKm: 4,
  },
  {
    id: "b2",
    cycleId: "c3",
    userId: "u1",
    startTime: "2025-12-03T15:00:00Z",
    endTime: "2025-12-03T16:30:00Z",
    pricePaid: 4.5,
    distanceKm: 7,
  },
];
